apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
    spec:
      containers:
        - name: chatbot-api
          image: chatbot-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "chatbot"
            - name: DB_USER
              value: "app"
            - name: DB_PASSWORD
              value: "app"
            - name: USE_OPENAI
              value: "false"
#            - name: OPENAI_API_KEY           
#              valueFrom:
#                secretKeyRef:
#                  name: openai-secret
#                  key: OPENAI_API_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-api-svc
spec:
  selector:
    app: chatbot-api
  ports:
    - port: 80
      targetPort: 8000
